apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app-python
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: devops-app-python
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: devops-app-python
    spec:
      containers:
      - name: devops-app-python
        image: deltation/devops-app-python
        ports:
        - containerPort: 5000