apiVersion: v1
kind: ConfigMap
metadata:
    name: app-config
    namespace: default
data:
    config.json: |-
        {{ printf "files/config.json" | .Files.Get | quote }}
# config.json: |-
#     {{- $files := .Files }}
#     {{- range tuple "config.json" }}
#     {{ . }}: |-
#             {{ $files.Get . }}
#     {{- end }}