- hosts: all

- name: Wait until system is ready
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Wait for apt list lock (Known to cause issues sometimes)
      raw: while fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do echo 'Waiting for apt list lock.' && sleep 10; done

  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip
    - geerlingguy.docker